name: My First Workflow

on: push

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Welcome Message , List, Car README
              run: |
                echo "My First Github Action Job"
                ls -lah
                cat README.md

            - name: Generate ASCII Artwork
              run: |
               
               cowsay -f dragon "Run for Cover, I am a DRAGON..... RAW!!!" >> dragon.txt
