name: ASCII Genertae file

# on: push

on: 
  workflow_dispatch: 

jobs:
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: List repo files 
              run: ls -ltr

            - name: Execute Shell Script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh

    second_job: 
        runs-on: ubuntu-latest
        needs: first_job
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: List repo files 
              run: ls -ltr

            - name: Execute Shell Script
              run: |
                chmod +x ascii-script.sh
                ./ascii-script.sh