name: Workflow Filters Explore

on: 
  workflow_dispatch: 
  push:
    branches: 
        - main
        - '!feature/*'
        - '!feature/**'

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
        - run: echo this workflow/job/step is executed for event type = ${{ github.event_name }}

      